### ISSUE TITLE
Doc Request: Migration options for hidden APIs

### ISSUE THREAD

**Issue by srvance** [zendesk/global_uid#84]
The v4 release hides several APIs like `with_connections` that are widely used in direct and indirect consumers. It doesn't appear that `with_servers` is a one for one replacement, so it's not clear how to update.

Can the docs provide a bit more explicit guidance on migrating away from the hidden APIs?

**Comment by mariozaizar** [comment]
Requested 👀 from top-contributors of this gem. We should ask @zendesk/classic-upgrade for help too.

**Comment by mriddle** [comment]
If you haven't seen it, there's a [doc on upgrading here](https://github.com/zendesk/global_uid/blob/master/docs/upgrading-to-4-0.md). 

The removal of `with_connections` was deliberate, it was a private API and clients shouldn't be using those connections directly. The responsibility of this gem is to provide IDs, nothing more.

If you _must_ do something with the connection, you would do it like so:
```ruby
GlobalUid::Base.with_servers do |server|
  puts "Allocation server name: #{server.name}"
  server.connection.select_all("SHOW TABLES").each do |row|
    puts "ID table Name: #{row.values.first}"
  end
end; nil
```

It's not recommended though. If a client is performing an action on the connection, consider upstreaming it by opening a pull request here and we can work together to ensure this gem is robust.

**Comment by srvance** [comment]
Thanks, @mriddle. I think the code snippet and explanation from your above comment should be added to the upgrade doc, perhaps with appropriate warnings.
